#FROM ubuntu
#RUN apt update
#RUN apt -y install apache2
#ADD . /var/www/html
#ENTRYPOINT apachectl -D FOREGROUND
#ENV name devops intellipath
FROM node:alpine
COPY . /app
WORKDIR /app
CMD node app.js
